version: '3'
services:
  backend_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  frontend_web:
    build:
      context: ../VirtualAssistant_Frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

