version: '3.8'
services:
  backend_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    networks:
      - my_network
    volumes:
      - .:/app
    depends_on:
      - database

  frontend_web:
    build:
      context: ../VirtualAssistant_Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - my_network
    volumes:
      - ../VirtualAssistant_Frontend/src:/src
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - backend_api
      - database

  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_USER_USERNAME: ${MONGO_INITDB_USER_USERNAME}
      MONGO_INITDB_USER_PASSWORD: ${MONGO_INITDB_USER_PASSWORD}
    ports:
      - '6000:27017'
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
       
networks:
  my_network:
    driver: bridge
