version: '3.8'
services:
  backend_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    networks:
      - my_network
    volumes:
      - .:/app
    depends_on:
      - mongodb_container

  frontend_web:
    build:
      context: ../VirtualAssistant_Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - my_network
    volumes:
      - ../VirtualAssistant_Frontend/src:/src
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - backend_api
      - mongodb_container

  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_USER_USERNAME: NongSnail
      MONGO_INITDB_USER_PASSWORD: 123456
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
       
networks:
  my_network:
    driver: bridge
