version: '3.8'
services:
  backend_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - my_network
    volumes:
      - .:/app

  frontend_web:
    build:
      context: ../VirtualAssistant_Frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - my_network
    volumes:
      - ../VirtualAssistant_Frontend/src:/src
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - backend_api
      
networks:
  my_network:
    driver: bridge
