name: VirtualAssistant Backend Actions Workflow

on:
  push:
    branches: ["master"]

env:
  USER_GITHUB: ${{secrets.USER_GITHUB}}
  PASSWORD_GITHUB: ${{secrets.PASSWORD_GITHUB}}

jobs:
  deploy-docker-to-server:
    runs-on:
      - self-hosted
    steps:
      - name: Stop docker-compose backend_api
        run: cd /home/narisara/project/VirtualAssistant_Backend &&
          docker-compose stop backend_api && docker-compose rm backend_api

      - name: Stop docker-compose frontend_web
        run: cd /home/narisara/project/VirtualAssistant_Backend &&
          docker-compose stop frontend_web && docker-compose rm frontend_web

      - name: Git pull backend
        run: cd /home/narisara/project/VirtualAssistant_Backend && git checkout . && git pull https://$USER_GITHUB:$PASSWORD_GITHUB@github.com/CP23NW1/VirtualAssistant_Backend

      - name: Git pull frontend
        run: cd /home/narisara/project/VirtualAssistant_Frontend_v2 && git checkout . && git pull https://$USER_GITHUB:$PASSWORD_GITHUB@github.com/CP23NW1/VirtualAssistant_Frontend_v2

      - name: Docker-compose up mongodb
        run: cd /home/narisara/project/VirtualAssistant_Backend && docker-compose up --build -d mongodb

      - name: Sleep for 20 seconds
        run: sleep 30s
        shell: bash

      - name: Docker-compose up backend_api
        run: cd /home/narisara/project/VirtualAssistant_Backend && docker-compose up --build -d backend_api

      - name: Docker-compose up frontend_web
        run: cd /home/narisara/project/VirtualAssistant_Backend && docker-compose up --build -d frontend_web
