name: VirtualAssistant Backend Actions Workflow

on:
  push:
    branches: [ "master" ]

env:
    USER_GITHUB : ${{secrets.USER_GITHUB}}
    PASSWORD_GITHUB : ${{secrets.PASSWORD_GITHUB}}

jobs:
    deploy-docker-to-server:
        runs-on: 
          - self-hosted
        steps:
        - name: Stop all docker-compose
          run:  cd /home/narisara/project/VirtualAssistant_Backend &&
                 sudo docker compose stop && sudo docker compose rm -f 
                
        - name: Git pull
          run:  cd /home/narisara/project/VirtualAssistant_Backend && git checkout . && git pull https://$USER_GITHUB:$PASSWORD_GITHUB@github.com/CP23NW1/VirtualAssistant_Backend

        - name: Docker-compose up 
          run:  cd /home/narisara/project/VirtualAssistant_Backend && sudo docker-compose up 

    
